// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY9vPDdtlmZ3uW1h2KrdXgaE8S9sww92o',
    appId: '1:851014026520:web:e761f41fdfc7b2d1950a6d',
    messagingSenderId: '851014026520',
    projectId: 'nasa-project-36c9e',
    authDomain: 'nasa-project-36c9e.firebaseapp.com',
    storageBucket: 'nasa-project-36c9e.appspot.com',
    measurementId: 'G-D12MEKYHV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk7Iqst3_7L1Ma6rYuIJxkrGnu3N3wv1k',
    appId: '1:851014026520:android:85d24f5d94c1609f950a6d',
    messagingSenderId: '851014026520',
    projectId: 'nasa-project-36c9e',
    storageBucket: 'nasa-project-36c9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwZFQqb-kGwfMMLIqOtrcgjrellJOH3as',
    appId: '1:851014026520:ios:c302e938dc126451950a6d',
    messagingSenderId: '851014026520',
    projectId: 'nasa-project-36c9e',
    storageBucket: 'nasa-project-36c9e.appspot.com',
    iosBundleId: 'com.example.nasaspaceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwZFQqb-kGwfMMLIqOtrcgjrellJOH3as',
    appId: '1:851014026520:ios:1923e39af412f2b8950a6d',
    messagingSenderId: '851014026520',
    projectId: 'nasa-project-36c9e',
    storageBucket: 'nasa-project-36c9e.appspot.com',
    iosBundleId: 'com.example.nasaspaceapp.RunnerTests',
  );
}
