// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2J6AIvDxBVXubkUhnHs7pxwUJUB9kWGI',
    appId: '1:499549956818:web:dc3c62240dfdfbf93a9b0b',
    messagingSenderId: '499549956818',
    projectId: 'nasaproject-1ac8c',
    authDomain: 'nasaproject-1ac8c.firebaseapp.com',
    storageBucket: 'nasaproject-1ac8c.appspot.com',
    measurementId: 'G-747R479P9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVvGa1b-B3v4GUYIN1kkGpBQ_ngpXpg6Y',
    appId: '1:499549956818:android:7a237f8a5a9a7a443a9b0b',
    messagingSenderId: '499549956818',
    projectId: 'nasaproject-1ac8c',
    storageBucket: 'nasaproject-1ac8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClQnDIYPu2K9TMwylHXKxFIynNE1-FoK8',
    appId: '1:499549956818:ios:fa85c37f4f7d874b3a9b0b',
    messagingSenderId: '499549956818',
    projectId: 'nasaproject-1ac8c',
    storageBucket: 'nasaproject-1ac8c.appspot.com',
    iosBundleId: 'com.example.nasaspaceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClQnDIYPu2K9TMwylHXKxFIynNE1-FoK8',
    appId: '1:499549956818:ios:d1d1227a221c676d3a9b0b',
    messagingSenderId: '499549956818',
    projectId: 'nasaproject-1ac8c',
    storageBucket: 'nasaproject-1ac8c.appspot.com',
    iosBundleId: 'com.example.nasaspaceapp.RunnerTests',
  );
}
